<?php include $_SERVER['DOCUMENT_ROOT']."/art/common/header.php"; ?>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>anxiety</h1></div>
<a href="/art/painting/anxiety/ali.php"><IMG src="/art/painting/anxiety/ali_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/anxiety/brian.php"><IMG src="/art/painting/anxiety/brian_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/anxiety/jacob.php"><IMG src="/art/painting/anxiety/jacob_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/anxiety/jorge.php"><IMG src="/art/painting/anxiety/jorge_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/anxiety/ken.php"><IMG src="/art/painting/anxiety/ken_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/anxiety/kensmoking.php"><IMG src="/art/painting/anxiety/kensmoking_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/anxiety/nelly.php"><IMG src="/art/painting/anxiety/nelly_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/anxiety/richard.php"><IMG src="/art/painting/anxiety/richard_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/anxiety/ryan.php"><IMG src="/art/painting/anxiety/ryan_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>city</h1></div>
<a href="/art/painting/city/10.php"><IMG src="/art/painting/city/10_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/11.php"><IMG src="/art/painting/city/11_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/1.php"><IMG src="/art/painting/city/1_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/2.php"><IMG src="/art/painting/city/2_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/3.php"><IMG src="/art/painting/city/3_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/4.php"><IMG src="/art/painting/city/4_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/5.php"><IMG src="/art/painting/city/5_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/6.php"><IMG src="/art/painting/city/6_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/7.php"><IMG src="/art/painting/city/7_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/8.php"><IMG src="/art/painting/city/8_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/city/9.php"><IMG src="/art/painting/city/9_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>cubes</h1></div>
<a href="/art/painting/cubes/adam.php"><IMG src="/art/painting/cubes/adam_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/at_the_cafe.php"><IMG src="/art/painting/cubes/at_the_cafe_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/bad_influence.php"><IMG src="/art/painting/cubes/bad_influence_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/before_dating.php"><IMG src="/art/painting/cubes/before_dating_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/black_face_with_red_lips.php"><IMG src="/art/painting/cubes/black_face_with_red_lips_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/brown_in_tears.php"><IMG src="/art/painting/cubes/brown_in_tears_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/friends.php"><IMG src="/art/painting/cubes/friends_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/getting_fresh_air.php"><IMG src="/art/painting/cubes/getting_fresh_air_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/giving_flowers.php"><IMG src="/art/painting/cubes/giving_flowers_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/handy_woman.php"><IMG src="/art/painting/cubes/handy_woman_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/looking_for_keys.php"><IMG src="/art/painting/cubes/looking_for_keys_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/madre_con_hijo.php"><IMG src="/art/painting/cubes/madre_con_hijo_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/martha.php"><IMG src="/art/painting/cubes/martha_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/melon.php"><IMG src="/art/painting/cubes/melon_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/my_conditions.php"><IMG src="/art/painting/cubes/my_conditions_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/my_dad.php"><IMG src="/art/painting/cubes/my_dad_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/my_sister.php"><IMG src="/art/painting/cubes/my_sister_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/nacked_old_lady.php"><IMG src="/art/painting/cubes/nacked_old_lady_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/nacked_sisters.php"><IMG src="/art/painting/cubes/nacked_sisters_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/nacked.php"><IMG src="/art/painting/cubes/nacked_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/new_love.php"><IMG src="/art/painting/cubes/new_love_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/parents.php"><IMG src="/art/painting/cubes/parents_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/ready_for_the_inteview.php"><IMG src="/art/painting/cubes/ready_for_the_inteview_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/rule_setter.php"><IMG src="/art/painting/cubes/rule_setter_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/sun_man.php"><IMG src="/art/painting/cubes/sun_man_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/tango_love.php"><IMG src="/art/painting/cubes/tango_love_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/the_bar.php"><IMG src="/art/painting/cubes/the_bar_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/the_family_picture.php"><IMG src="/art/painting/cubes/the_family_picture_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/tuesday.php"><IMG src="/art/painting/cubes/tuesday_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/cubes/with_a_kid.php"><IMG src="/art/painting/cubes/with_a_kid_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>ghosts</h1></div>
<a href="/art/painting/ghosts/cigarettes.php"><IMG src="/art/painting/ghosts/cigarettes_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/confusing.php"><IMG src="/art/painting/ghosts/confusing_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/cross.php"><IMG src="/art/painting/ghosts/cross_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/death.php"><IMG src="/art/painting/ghosts/death_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/good_by.php"><IMG src="/art/painting/ghosts/good_by_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/jimmy_jams.php"><IMG src="/art/painting/ghosts/jimmy_jams_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/lost.php"><IMG src="/art/painting/ghosts/lost_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/men.php"><IMG src="/art/painting/ghosts/men_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/the_party.php"><IMG src="/art/painting/ghosts/the_party_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/ghosts/the_three_levels.php"><IMG src="/art/painting/ghosts/the_three_levels_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>hollywood</h1></div>
<a href="/art/painting/hollywood/actors.php"><IMG src="/art/painting/hollywood/actors_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/hollywood/danny.php"><IMG src="/art/painting/hollywood/danny_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/hollywood/jason.php"><IMG src="/art/painting/hollywood/jason_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/hollywood/jimmy.php"><IMG src="/art/painting/hollywood/jimmy_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/hollywood/jose.php"><IMG src="/art/painting/hollywood/jose_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/hollywood/mike.php"><IMG src="/art/painting/hollywood/mike_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/hollywood/ron.php"><IMG src="/art/painting/hollywood/ron_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/hollywood/steven.php"><IMG src="/art/painting/hollywood/steven_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/hollywood/warren.php"><IMG src="/art/painting/hollywood/warren_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>lines</h1></div>
<a href="/art/painting/lines/animal_face.php"><IMG src="/art/painting/lines/animal_face_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/lines/long_face.php"><IMG src="/art/painting/lines/long_face_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/lines/the_aunt.php"><IMG src="/art/painting/lines/the_aunt_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/lines/the_bird_face.php"><IMG src="/art/painting/lines/the_bird_face_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/lines/the_flag.php"><IMG src="/art/painting/lines/the_flag_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/lines/the_middle_east.php"><IMG src="/art/painting/lines/the_middle_east_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/lines/young_face.php"><IMG src="/art/painting/lines/young_face_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>mix</h1></div>
<a href="/art/painting/mix/3faces.php"><IMG src="/art/painting/mix/3faces_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/abuelo_tango.php"><IMG src="/art/painting/mix/abuelo_tango_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/alison_jorge.php"><IMG src="/art/painting/mix/alison_jorge_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/biggest_clown.php"><IMG src="/art/painting/mix/biggest_clown_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/bird_head.php"><IMG src="/art/painting/mix/bird_head_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/black_body.php"><IMG src="/art/painting/mix/black_body_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/black_hair.php"><IMG src="/art/painting/mix/black_hair_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/black_terminator.php"><IMG src="/art/painting/mix/black_terminator_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/blue_eye_lashes.php"><IMG src="/art/painting/mix/blue_eye_lashes_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/blue_woman_with_flower.php"><IMG src="/art/painting/mix/blue_woman_with_flower_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/body_of_woman.php"><IMG src="/art/painting/mix/body_of_woman_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/bow_yellow_man.php"><IMG src="/art/painting/mix/bow_yellow_man_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/bringing_food.php"><IMG src="/art/painting/mix/bringing_food_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/clown_and_ghost.php"><IMG src="/art/painting/mix/clown_and_ghost_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/coming_through.php"><IMG src="/art/painting/mix/coming_through_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/corredor.php"><IMG src="/art/painting/mix/corredor_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/dacing_in_new_york.php"><IMG src="/art/painting/mix/dacing_in_new_york_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/dark_ghost.php"><IMG src="/art/painting/mix/dark_ghost_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/deep_gray_red_eye_lashes.php"><IMG src="/art/painting/mix/deep_gray_red_eye_lashes_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/el_pueblo.php"><IMG src="/art/painting/mix/el_pueblo_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/ethan_and_erin.php"><IMG src="/art/painting/mix/ethan_and_erin_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/face_of_man.php"><IMG src="/art/painting/mix/face_of_man_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/face_of_woman_with_yellow_and_red.php"><IMG src="/art/painting/mix/face_of_woman_with_yellow_and_red_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/father_child_dark_and_yellow.php"><IMG src="/art/painting/mix/father_child_dark_and_yellow_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/father_son_in_red.php"><IMG src="/art/painting/mix/father_son_in_red_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/flying_guitar_man.php"><IMG src="/art/painting/mix/flying_guitar_man_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/guitar_man.php"><IMG src="/art/painting/mix/guitar_man_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/in_buenos_aires.php"><IMG src="/art/painting/mix/in_buenos_aires_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/in_the_closet.php"><IMG src="/art/painting/mix/in_the_closet_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/jorge_carla.php"><IMG src="/art/painting/mix/jorge_carla_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/living_room_holding_yellow_flower.php"><IMG src="/art/painting/mix/living_room_holding_yellow_flower_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/living_room_on_the_couch.php"><IMG src="/art/painting/mix/living_room_on_the_couch_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/lonley_woman.php"><IMG src="/art/painting/mix/lonley_woman_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/looking_at_you.php"><IMG src="/art/painting/mix/looking_at_you_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/lost_it.php"><IMG src="/art/painting/mix/lost_it_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/mam_face.php"><IMG src="/art/painting/mix/mam_face_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/man_and_woman_with_unbrella.php"><IMG src="/art/painting/mix/man_and_woman_with_unbrella_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/man_dancing_in_living_room.php"><IMG src="/art/painting/mix/man_dancing_in_living_room_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/manwithhellohead.php"><IMG src="/art/painting/mix/manwithhellohead_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/meinorange.php"><IMG src="/art/painting/mix/meinorange_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/mewithblackeyelashes.php"><IMG src="/art/painting/mix/mewithblackeyelashes_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/modre_con_hija.php"><IMG src="/art/painting/mix/modre_con_hija_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/mother_and_daughter.php"><IMG src="/art/painting/mix/mother_and_daughter_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/mother_daughter.php"><IMG src="/art/painting/mix/mother_daughter_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/mother_son.php"><IMG src="/art/painting/mix/mother_son_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/my_only_love.php"><IMG src="/art/painting/mix/my_only_love_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/negotiation.php"><IMG src="/art/painting/mix/negotiation_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/on_the_wall.php"><IMG src="/art/painting/mix/on_the_wall_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/out_in_the_park.php"><IMG src="/art/painting/mix/out_in_the_park_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/plantas.php"><IMG src="/art/painting/mix/plantas_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/purple_black_man_with_yellow_hat.php"><IMG src="/art/painting/mix/purple_black_man_with_yellow_hat_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/ready_for_tonight.php"><IMG src="/art/painting/mix/ready_for_tonight_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/red_cheeks.php"><IMG src="/art/painting/mix/red_cheeks_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/red_hair.php"><IMG src="/art/painting/mix/red_hair_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/run_of_the_lovers.php"><IMG src="/art/painting/mix/run_of_the_lovers_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/speed.php"><IMG src="/art/painting/mix/speed_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/tall_mother_and_son.php"><IMG src="/art/painting/mix/tall_mother_and_son_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/thailand.php"><IMG src="/art/painting/mix/thailand_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/the_consert.php"><IMG src="/art/painting/mix/the_consert_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/the_young_lover.php"><IMG src="/art/painting/mix/the_young_lover_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/things_in_head.php"><IMG src="/art/painting/mix/things_in_head_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/to_work.php"><IMG src="/art/painting/mix/to_work_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/tree_1.php"><IMG src="/art/painting/mix/tree_1_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/tree_2.php"><IMG src="/art/painting/mix/tree_2_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/tree_3.php"><IMG src="/art/painting/mix/tree_3_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/tree_sisters.php"><IMG src="/art/painting/mix/tree_sisters_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/two_faces.php"><IMG src="/art/painting/mix/two_faces_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/up_to_no_good.php"><IMG src="/art/painting/mix/up_to_no_good_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/vale.php"><IMG src="/art/painting/mix/vale_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/will_work_for_food_woman_child.php"><IMG src="/art/painting/mix/will_work_for_food_woman_child_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/with_big_teeth.php"><IMG src="/art/painting/mix/with_big_teeth_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/with_my_mother.php"><IMG src="/art/painting/mix/with_my_mother_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/woman_blue_turban.php"><IMG src="/art/painting/mix/woman_blue_turban_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/woman_in_blue_dress.php"><IMG src="/art/painting/mix/woman_in_blue_dress_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/woman_in_blue_dress_with_yellow_turban.php"><IMG src="/art/painting/mix/woman_in_blue_dress_with_yellow_turban_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/woman_of_the_future.php"><IMG src="/art/painting/mix/woman_of_the_future_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/woman_red_hair.php"><IMG src="/art/painting/mix/woman_red_hair_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/yellow_blue_eyes.php"><IMG src="/art/painting/mix/yellow_blue_eyes_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/mix/yellow_man_with_cross.php"><IMG src="/art/painting/mix/yellow_man_with_cross_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>paper</h1></div>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>pigs</h1></div>
<a href="/art/painting/pigs/america.php"><IMG src="/art/painting/pigs/america_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/pigs/england.php"><IMG src="/art/painting/pigs/england_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/pigs/france.php"><IMG src="/art/painting/pigs/france_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/pigs/germany.php"><IMG src="/art/painting/pigs/germany_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/pigs/japan.php"><IMG src="/art/painting/pigs/japan_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/pigs/rome.php"><IMG src="/art/painting/pigs/rome_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>politics</h1></div>
<a href="/art/painting/politics/animal_farm.php"><IMG src="/art/painting/politics/animal_farm_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/politics/business.php"><IMG src="/art/painting/politics/business_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/politics/fair.php"><IMG src="/art/painting/politics/fair_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/politics/fox.php"><IMG src="/art/painting/politics/fox_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/politics/political_speech.php"><IMG src="/art/painting/politics/political_speech_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>turnheads</h1></div>
<a href="/art/painting/turnheads/boy_with_plant.php"><IMG src="/art/painting/turnheads/boy_with_plant_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/coming_home_from_work.php"><IMG src="/art/painting/turnheads/coming_home_from_work_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/dancer_and_guitar_man.php"><IMG src="/art/painting/turnheads/dancer_and_guitar_man_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/dawn_at_the_park.php"><IMG src="/art/painting/turnheads/dawn_at_the_park_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/family_in_glass.php"><IMG src="/art/painting/turnheads/family_in_glass_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/family_of_three.php"><IMG src="/art/painting/turnheads/family_of_three_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/first_day_of_school.php"><IMG src="/art/painting/turnheads/first_day_of_school_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/fother_and_mother_dancing.php"><IMG src="/art/painting/turnheads/fother_and_mother_dancing_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/girl_boy_in_glass.php"><IMG src="/art/painting/turnheads/girl_boy_in_glass_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/girl_in_glass.php"><IMG src="/art/painting/turnheads/girl_in_glass_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/hello.php"><IMG src="/art/painting/turnheads/hello_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/in_the_purple_room.php"><IMG src="/art/painting/turnheads/in_the_purple_room_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/man_in_glass.php"><IMG src="/art/painting/turnheads/man_in_glass_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/my_fish.php"><IMG src="/art/painting/turnheads/my_fish_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/perl.php"><IMG src="/art/painting/turnheads/perl_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/purple_and_green.php"><IMG src="/art/painting/turnheads/purple_and_green_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/ready_for_the_party.php"><IMG src="/art/painting/turnheads/ready_for_the_party_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/the_blue_crew.php"><IMG src="/art/painting/turnheads/the_blue_crew_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/the_celebration.php"><IMG src="/art/painting/turnheads/the_celebration_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/the_hug.php"><IMG src="/art/painting/turnheads/the_hug_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/the_kids.php"><IMG src="/art/painting/turnheads/the_kids_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/the_red_crew.php"><IMG src="/art/painting/turnheads/the_red_crew_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/the_small_family.php"><IMG src="/art/painting/turnheads/the_small_family_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/woman_trapped_in_glass.php"><IMG src="/art/painting/turnheads/woman_trapped_in_glass_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/turnheads/woman_with_flower.php"><IMG src="/art/painting/turnheads/woman_with_flower_tumb.jpg" class="allThumbs"></a>
<div class="panel panel-heading" align="left" style="color: gray;"><h1>war</h1></div>
<a href="/art/painting/war/birth.php"><IMG src="/art/painting/war/birth_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/collateral_damage.php"><IMG src="/art/painting/war/collateral_damage_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/coming_for_freedom.php"><IMG src="/art/painting/war/coming_for_freedom_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/dealer.php"><IMG src="/art/painting/war/dealer_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/done.php"><IMG src="/art/painting/war/done_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/general.php"><IMG src="/art/painting/war/general_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/holy_man.php"><IMG src="/art/painting/war/holy_man_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/liberation.php"><IMG src="/art/painting/war/liberation_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/medicine.php"><IMG src="/art/painting/war/medicine_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/piss.php"><IMG src="/art/painting/war/piss_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/religion_kills.php"><IMG src="/art/painting/war/religion_kills_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/run_woman.php"><IMG src="/art/painting/war/run_woman_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/smoker.php"><IMG src="/art/painting/war/smoker_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/the_winner.php"><IMG src="/art/painting/war/the_winner_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/worker.php"><IMG src="/art/painting/war/worker_tumb.jpg" class="allThumbs"></a>
<a href="/art/painting/war/yellow_gun.php"><IMG src="/art/painting/war/yellow_gun_tumb.jpg" class="allThumbs"></a>
<?php include $_SERVER['DOCUMENT_ROOT']."/art/common/footer.php"; ?>