<?php include $_SERVER['DOCUMENT_ROOT']."/art/template/classes.php"; ?>

<?php
$paintingTitle = "Mix";
$arrayOfImages = array(
new Painting('mix', '3faces', '3faces'),
new Painting('mix', 'abuelo_tango', 'Abuelo Tango'),
new Painting('mix', 'biggest_clown', 'Biggest Clown'),
new Painting('mix', 'black_terminator', 'Black Terminator'),
new Painting('mix', 'blue_eye_lashes', 'Blue Eye Lashes'),
new Painting('mix', 'blue_woman_with_flower', 'Blue Woman With Flower'),
new Painting('mix', 'body_of_woman', 'Body Of Woman'),
new Painting('mix', 'bow_yellow_man', 'Bow Yellow Man'),
new Painting('mix', 'bringing_food', 'Bringing Food'),
new Painting('mix', 'clown_and_ghost', 'Clown And Ghost'),
new Painting('mix', 'corredor', 'Corredor'),
new Painting('mix', 'dacing_in_new_york', 'Dacing In New York'),
new Painting('mix', 'parents', 'Parents'),
new Painting('mix', 'dark_ghost', 'Dark Ghost'),
new Painting('mix', 'deep_gray_red_eye_lashes', 'Deep Gray Red Eye Lashes'),
new Painting('mix', 'el_pueblo', 'El Pueblo'),
new Painting('mix', 'ethan_and_erin', 'Ethan And Erin'),
new Painting('mix', 'face_of_man', 'Face Of Man'),
new Painting('mix', 'face_of_woman_with_yellow_and_red', 'Face Of Woman With Yellow And Red'),
new Painting('mix', 'father_child_dark_and_yellow', 'Father Child Dark And Yellow'),
new Painting('mix', 'father_son_in_red', 'Father Son In Red'),
new Painting('mix', 'flying_guitar_man', 'Flying Guitar Man'),
new Painting('mix', 'guitar_man', 'Guitar Man'),
new Painting('mix', 'alison_jorge', 'Alison Jorge'),
new Painting('mix', 'in_buenos_aires', 'In Buenos Aires'),
new Painting('mix', 'in_the_closet', 'In The Closet'),
new Painting('mix', 'jorge_carla', 'Jorge Carla'),
new Painting('mix', 'living_room_holding_yellow_flower', 'Living Room Holding Yellow Flower'),
new Painting('mix', 'living_room_on_the_couch', 'Living Room On The Couch'),
new Painting('mix', 'lonley_woman', 'Lonley Woman'),
new Painting('mix', 'looking_at_you', 'Looking At You'),
new Painting('mix', 'lost_it', 'Lost It'),
new Painting('mix', 'mam_face', 'Mam Face'),
new Painting('mix', 'man_and_woman_with_unbrella', 'Man And Woman With Unbrella'),
new Painting('mix', 'man_dancing_in_living_room', 'Man Dancing In Living Room'),
new Painting('mix', 'manwithhellohead', 'Manwithhellohead'),
new Painting('mix', 'meinorange', 'Me In Orange'),
new Painting('mix', 'mewithblackeyelashes', 'Me With Black Eye Lashes'),
new Painting('mix', 'modre_con_hija', 'Modre Con Hija'),
new Painting('mix', 'mother_and_daughter', 'Mother And Daughter'),
new Painting('mix', 'mother_daughter', 'Mother Daughter'),
new Painting('mix', 'on_the_wall', 'On The Wall'),
new Painting('mix', 'out_in_the_park', 'Out In The Park'),
new Painting('mix', 'plantas', 'Plantas'),
new Painting('mix', 'purple_black_man_with_yellow_hat', 'Purple Black Man With Yellow Hat'),
new Painting('mix', 'ready_for_tonight', 'Ready For Tonight'),
new Painting('mix', 'red_cheeks', 'Red Cheeks'),
new Painting('mix', 'red_hair', 'Red Hair'),
new Painting('mix', 'run_of_the_lovers', 'Run Of The Lovers'),
new Painting('mix', 'thailand', 'Thailand'),
new Painting('mix', 'the_consert', 'The Consert'),
new Painting('mix', 'the_young_lover', 'The Young Lover'),
new Painting('mix', 'things_in_head', 'Things In Head'),
new Painting('mix', 'to_work', 'To Work'),
new Painting('mix', 'yellow_man_with_cross', 'Yellow Man With Cross'),
new Painting('mix', 'tree_1', 'Tree 1'),
new Painting('mix', 'tree_2', 'Tree 2'),
new Painting('mix', 'tree_3', 'Tree 3'),
new Painting('mix', 'tree_sisters', 'Tree Sisters'),
new Painting('mix', 'two_faces', 'Two Faces'),
new Painting('mix', 'up_to_no_good', 'Up To No Good'),
new Painting('mix', 'vale', 'Vale'),
new Painting('mix', 'will_work_for_food_woman_child', 'Will Work For Food Woman Child'),
new Painting('mix', 'with_big_teeth', 'With Big Teeth'),
new Painting('mix', 'with_my_mother', 'With My Mother'),
new Painting('mix', 'woman_blue_turban', 'Woman Blue Turban'),
new Painting('mix', 'woman_in_blue_dress', 'Woman In Blue Dress'),
new Painting('mix', 'woman_in_blue_dress_with_yellow_turban', 'Woman In Blue Dress With Yellow Turban'),
new Painting('mix', 'woman_of_the_future', 'Woman Of The Future'),
new Painting('mix', 'woman_red_hair', 'Woman Red Hair'),
new Painting('mix', 'yellow_blue_eyes', 'Yellow Blue Eyes'),
new Painting('mix', 'bird_head', 'Bird Head'),
new Painting('mix', 'tall_mother_and_son', 'Tall Mother And Son'),
new Painting('mix', 'black_body', 'Black Body'),
new Painting('mix', 'black_hair', 'Black Hair')
	);
?>

<?php include $_SERVER['DOCUMENT_ROOT']."/art/template/content_t.php"; ?>