CREATE TABLE authorities (
  username varchar(100) NOT NULL,
  authority varchar(50) NOT NULL,
  created_by varchar(100) DEFAULT NULL,
  updated_by varchar(100) DEFAULT NULL,
  created_time datetime DEFAULT NULL,
  updated_time datetime DEFAULT NULL,
  UNIQUE KEY ix_auth_username (username,authority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;